// <auto-generated />
namespace SilkScreenOrder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedmodelschemepart2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedmodelschemepart2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706162302337_updated model scheme part 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
