// <auto-generated />
namespace SilkScreenOrder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmaxlengthtonumberofcolors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmaxlengthtonumberofcolors));
        
        string IMigrationMetadata.Id
        {
            get { return "201706181846190_added max length to number of colors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
